spring:
  profiles:
    include: base
    active: base, interceptor

---
spring:
  profiles: interceptor
  datasource:
    username: peter

server:
  port: 8082
  servlet:
    context-path: /shogun-gs-interceptor

---
spring:
  profiles: interceptor-dev
  datasource:
    url: jdbc:postgresql://localhost:5555/shogun?currentSchema=interceptor

server:
  port: 8082
  servlet:
    context-path: /shogun-gs-interceptor

interceptor:
  namespaceBoundUrl: true
  defaultOwsUrl: http://localhost:1234/geoserver
  namespaces:
    - namespace: SHOGUN
      url: http://localhost:1234/geoserver/SHOGUN




